### ISSUE TITLE
Can't find backups to restore

### ISSUE THREAD

**Issue by gruaig** [spotify/cassandra-medusa#15]
Python 3.7.5 (default, Nov 14 2019, 13:29:23) 
Docker debian build.

Config file

> [cassandra]
#stop_cmd = /etc/init.d/cassandra stop
#start_cmd = /etc/init.d/cassandra start
#config_file = <path to cassandra.yaml. Defaults to /etc/cassandra/cassandra.yaml>
cql_username = cassandra
cql_password = cassandra
#check_running = <Command ran to verify if Cassandra is running on a node. Defaults to "nodetool version">

>[storage]
storage_provider = local
base_path = /home
bucket_name = shed 

>[restore]
;health_check = <Which ports to check when verifying a node restored properly. Options are 'cql' (default), 'thrift', 'all'.>
;query = <CQL query to run after a restore to verify it went OK>
;expected_rows = <Number of rows expected to be returned when the query runs. Not checked if not specified.>
;expected_result = <Coma separated string representation of values returned by the query. Checks only 1st row returned, and only if specified>

 root@uk_staging-cassandra-03:/etc/medusa# medusa backup
[2019-11-19 14:23:52] INFO: Monitoring provider is noop
[2019-11-19 14:23:52] WARNING: is ccm : 0
[2019-11-19 14:23:52] ERROR: This error happened during the backup: Error: Backup 2019111914 already exists
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/medusa/backup.py", line 191, in main
    raise IOError('Error: Backup {} already exists'.format(backup_name))
OSError: Error: Backup 2019111914 already exists
 
Proof the backup exists ^ Which was created a few min before.
I've added some prints to the command so you can see config.

root@uk_staging-cassandra-03:/etc/medusa# medusa list-backups
StorageConfig(bucket_name='shed', key_file=None, prefix=None, fqdn='uk_staging-cassandra-3', host_file_separator=',', storage_provider='local', api_key_or_username=None, api_secret_or_password=None, base_path='/home', max_backup_age='0', max_backup_count='0', api_profile='default')

**Comment by adejanovski** [comment]
Hi @gruaig, could you open issues [in the tlp fork](https://github.com/thelastpickle/cassandra-medusa/issues) instead? 
This repository is deprecated now.

Thanks!

**Comment by adejanovski** [comment]
@gruaig, could you run the following command?

`medusa build-index`

Then try again to list backups using : `medusa -v list-backups`
You can also try : `medusa -v list-backups --show-all`

There's a chance your backup folder was created but the backup didn't go through correctly, which could leave the bucket in a state where it's not showing up when listing backups.

**Comment by gruaig** [comment]
Hi,

Yeah I've tried that in the past the results is the same

root@uk_staging-cassandra-03:/# medusa build-index
[2019-11-20 13:52:39] WARNING: is ccm : 0
[2019-11-20 13:52:39] INFO: processing uk_staging-cassandra-01
[2019-11-20 13:52:39] INFO: processing uk_staging-cassandra-02
[2019-11-20 13:52:39] INFO: processing uk_staging-cassandra-3
[2019-11-20 13:52:39] INFO: processing uk_staging-cassandra-04
root@uk_staging-cassandra-03:/# medusa -v list-backups --show-all
[2019-11-20 13:52:44] DEBUG: Loading configuration from
/etc/medusa/medusa.ini
[2019-11-20 13:52:44] INFO: No backups found in index. Consider running
"medusa build-index" if you have some backups
root@uk_staging-cassandra-03:/#

**Comment by adejanovski** [comment]
Could you check the local folder where you're storing the backups? 
Should be under `/home/shed` based on your configuration.
Is it a shared folder in your cluster?
What do you see as content there? You can check the expected folder structure there : https://github.com/thelastpickle/cassandra-medusa/blob/master/docs/design.md#data-structures

**Comment by gruaig** [comment]
Hey

This file is not shared over the cluster should it be. It is a local backup
of a cluster.? Ye the full data structure of that node exists. It's just
the commands are looking or can't read it. I've checked permissions etc.
Everything seems to be fine.

**Comment by gruaig** [comment]
Hi

I have changed the path. And here is my structure.

root@uk_staging-cassandra-03:/# medusa restore-node --backup-name
uk_staging-cassandra-3
[2019-11-20 15:19:55] ERROR: No such backup
root@uk_staging-cassandra-03:/# medusa restore-node --backup-name
/db-snapshots/local/uk_staging-cassandra-3
[2019-11-20 15:20:04] ERROR: No such backup
root@uk_staging-cassandra-03:/# medusa restore-node --backup-name
/db-snapshots/local/uk_staging-cassandra-3/^C
root@uk_staging-cassandra-03:/# ls /db-snapshots/local/
index  uk_staging-cassandra-3
root@uk_staging-cassandra-03:/# ls
/db-snapshots/local/uk_staging-cassandra-3/
2019112014  data
root@uk_staging-cassandra-03:/# ls
/db-snapshots/local/uk_staging-cassandra-3/*
/db-snapshots/local/uk_staging-cassandra-3/2019112014:
meta

/db-snapshots/local/uk_staging-cassandra-3/data:
main  orders  shared  system  system_auth  system_schema
root@uk_staging-cassandra-03:/#

Sean

**Comment by adejanovski** [comment]
Continuing the conversation here : https://github.com/thelastpickle/cassandra-medusa/issues/12
